export const languages = [
  {
    code: "af",
    label: "Afrikaans",
    native: "Afrikaans",
    flag: "🇿🇦",
    preview: "Hallo, welkom!",
  },
  {
    code: "sq",
    label: "Albanian",
    native: "Shqip",
    flag: "🇦🇱",
    preview: "Përshëndetje, mirë se vini!",
  },
  {
    code: "ar",
    label: "Arabic",
    native: "العربية",
    flag: "🇸🇦",
    preview: "مرحبا، أهلا وسهلا!",
  },
  {
    code: "hy",
    label: "Armenian",
    native: "Հայերեն",
    flag: "🇦🇲",
    preview: "Բարեւ, բարի գալուստ!",
  },
  {
    code: "bn",
    label: "Bengali",
    native: "বাংলা",
    flag: "🇧🇩",
    preview: "হ্যালো, স্বাগতম!",
  },
  {
    code: "bs",
    label: "Bosnian",
    native: "Bosanski",
    flag: "🇧🇦",
    preview: "Zdravo, dobrodošli!",
  },
  {
    code: "ca",
    label: "Catalan",
    native: "Català",
    flag: "🇪🇸",
    preview: "Hola, benvingut!",
  },
  {
    code: "zh",
    label: "Chinese",
    native: "中文",
    flag: "🇨🇳",
    preview: "你好，欢迎！",
  },
  {
    code: "hr",
    label: "Croatian",
    native: "Hrvatski",
    flag: "🇭🇷",
    preview: "Zdravo, dobrodošli!",
  },
  {
    code: "cs",
    label: "Czech",
    native: "Čeština",
    flag: "🇨🇿",
    preview: "Ahoj, vítej!",
  },
  {
    code: "da",
    label: "Danish",
    native: "Dansk",
    flag: "🇩🇰",
    preview: "Hej, velkommen!",
  },
  {
    code: "nl",
    label: "Dutch",
    native: "Nederlands",
    flag: "🇳🇱",
    preview: "Hallo, welkom!",
  },
  {
    code: "en",
    label: "English",
    native: "English",
    flag: "🇺🇸",
    preview: "Hello, welcome!",
  },
  {
    code: "et",
    label: "Estonian",
    native: "Eesti",
    flag: "🇪🇪",
    preview: "Tere, tere tulemast!",
  },
  {
    code: "fi",
    label: "Finnish",
    native: "Suomi",
    flag: "🇫🇮",
    preview: "Hei, tervetuloa!",
  },
  {
    code: "fr",
    label: "French",
    native: "Français",
    flag: "🇫🇷",
    preview: "Bonjour, bienvenue!",
  },
  {
    code: "ka",
    label: "Georgian",
    native: "ქართული",
    flag: "🇬🇪",
    preview: "გამარჯობა, კეთილი იყოს თქვენი მობრძანება!",
  },
  {
    code: "de",
    label: "German",
    native: "Deutsch",
    flag: "🇩🇪",
    preview: "Hallo, willkommen!",
  },
  {
    code: "el",
    label: "Greek",
    native: "Ελληνικά",
    flag: "🇬🇷",
    preview: "Γεια σας, καλώς ήρθατε!",
  },
  {
    code: "gu",
    label: "Gujarati",
    native: "ગુજરાતી",
    flag: "🇮🇳",
    preview: "નમસ્તે, સ્વાગત છે!",
  },
  {
    code: "he",
    label: "Hebrew",
    native: "עברית",
    flag: "🇮🇱",
    preview: "שלום, ברוך הבא!",
  },
  {
    code: "hi",
    label: "Hindi",
    native: "हिन्दी",
    flag: "🇮🇳",
    preview: "नमस्ते, स्वागत है!",
  },
  {
    code: "hu",
    label: "Hungarian",
    native: "Magyar",
    flag: "🇭🇺",
    preview: "Helló, üdvözöljük!",
  },
  {
    code: "id",
    label: "Indonesian",
    native: "Bahasa Indonesia",
    flag: "🇮🇩",
    preview: "Halo, selamat datang!",
  },
  {
    code: "ga",
    label: "Irish",
    native: "Gaelige",
    flag: "🇮🇪",
    preview: "Dia duit, fáilte!",
  },
  {
    code: "it",
    label: "Italian",
    native: "Italiano",
    flag: "🇮🇹",
    preview: "Ciao, benvenuto!",
  },
  {
    code: "ja",
    label: "Japanese",
    native: "日本語",
    flag: "🇯🇵",
    preview: "こんにちは、ようこそ！",
  },
  {
    code: "kk",
    label: "Kazakh",
    native: "Қазақша",
    flag: "🇰🇿",
    preview: "Сәлем, қош келдіңіз!",
  },
  {
    code: "ko",
    label: "Korean",
    native: "한국어",
    flag: "🇰🇷",
    preview: "안녕하세요, 환영합니다!",
  },
  {
    code: "lv",
    label: "Latvian",
    native: "Latviešu",
    flag: "🇱🇻",
    preview: "Sveiki, laipni lūdzam!",
  },
  {
    code: "lt",
    label: "Lithuanian",
    native: "Lietuvių",
    flag: "🇱🇹",
    preview: "Labas, sveiki atvykę!",
  },
  {
    code: "ms",
    label: "Malay",
    native: "Bahasa Melayu",
    flag: "🇲🇾",
    preview: "Helo, selamat datang!",
  },
  {
    code: "no",
    label: "Norwegian",
    native: "Norsk",
    flag: "🇳🇴",
    preview: "Hei, velkommen!",
  },
  {
    code: "fa",
    label: "Persian",
    native: "فارسی",
    flag: "🇮🇷",
    preview: "سلام، خوش آمدید!",
  },
  {
    code: "pl",
    label: "Polish",
    native: "Polski",
    flag: "🇵🇱",
    preview: "Cześć, witaj!",
  },
  {
    code: "pt",
    label: "Portuguese",
    native: "Português",
    flag: "🇵🇹",
    preview: "Olá, bem-vindo!",
  },
  {
    code: "pa",
    label: "Punjabi",
    native: "ਪੰਜਾਬੀ",
    flag: "🇮🇳",
    preview: "ਨਮਸਤੇ, ਜੀ ਆਇਆਂ ਨੂੰ!",
  },
  {
    code: "ro",
    label: "Romanian",
    native: "Română",
    flag: "🇷🇴",
    preview: "Bună, bine ai venit!",
  },
  {
    code: "ru",
    label: "Russian",
    native: "Русский",
    flag: "🇷🇺",
    preview: "Привет, добро пожаловать!",
  },
  {
    code: "sr",
    label: "Serbian",
    native: "Српски",
    flag: "🇷🇸",
    preview: "Здраво, добродошли!",
  },
  {
    code: "sk",
    label: "Slovak",
    native: "Slovenčina",
    flag: "🇸🇰",
    preview: "Ahoj, vitaj!",
  },
  {
    code: "sl",
    label: "Slovenian",
    native: "Slovenščina",
    flag: "🇸🇮",
    preview: "Zdravo, dobrodošli!",
  },
  {
    code: "es",
    label: "Spanish",
    native: "Español",
    flag: "🇪🇸",
    preview: "¡Hola, bienvenido!",
  },
  {
    code: "sw",
    label: "Swahili",
    native: "Kiswahili",
    flag: "🇹🇿",
    preview: "Habari, karibu!",
  },
  {
    code: "sv",
    label: "Swedish",
    native: "Svenska",
    flag: "🇸🇪",
    preview: "Hej, välkommen!",
  },
  {
    code: "ta",
    label: "Tamil",
    native: "தமிழ்",
    flag: "🇮🇳",
    preview: "வணக்கம், வரவேற்கிறோம்!",
  },
  {
    code: "te",
    label: "Telugu",
    native: "తెలుగు",
    flag: "🇮🇳",
    preview: "హలో, స్వాగతం!",
  },
  {
    code: "th",
    label: "Thai",
    native: "ไทย",
    flag: "🇹🇭",
    preview: "สวัสดี ยินดีต้อนรับ!",
  },
  {
    code: "tr",
    label: "Turkish",
    native: "Türkçe",
    flag: "🇹🇷",
    preview: "Merhaba, hoş geldiniz!",
  },
  {
    code: "uk",
    label: "Ukrainian",
    native: "Українська",
    flag: "🇺🇦",
    preview: "Привіт, ласкаво просимо!",
  },
  {
    code: "ur",
    label: "Urdu",
    native: "اردو",
    flag: "🇵🇰",
    preview: "ہیلو، خوش آمدید!",
  },
  {
    code: "vi",
    label: "Vietnamese",
    native: "Tiếng Việt",
    flag: "🇻🇳",
    preview: "Chào bạn, chào mừng!",
  },
  {
    code: "cy",
    label: "Welsh",
    native: "Cymraeg",
    flag: "🇬🇧",
    preview: "Helo, croeso!",
  },
];